const db = require('../db');

async function debugNF() {
  try {
    await db.initialize();
    
    console.log('--- BUSCANDO POR NUMERO DA NOTA ---');
    // Buscaremos notas que tenham o número contendo a sequência fornecida
    const sqlNF = `
      SELECT XML_FIL, XML_NUMNF, XML_CHAVE, XML_EMIT, XML_NOMEMT, XML_VLRDOC, XML_STATUS, XML_CATEGORIA 
      FROM (
        SELECT XM.*,
          CASE
            WHEN XML_STATUS = 'Rejeitada' OR XML_STATUS LIKE 'Classificada%' OR XML_STATUS LIKE 'Lançada%' THEN 'Concluido'
            ELSE 'Pendente'
          END as XML_CATEGORIA
        FROM (
          SELECT 
            XM.XML_CHAVE,
            TRIM(XM.XML_NUMNF) as XML_NUMNF,
            TRIM(XM.XML_NOMEMT) as XML_NOMEMT,
            XM.XML_EMISSA,
            XM.XML_RECEB,
            XM.XML_DTRVLD,
            XM.XML_VLRDOC,
            TRIM(XM.XML_TIPODC) as XML_TIPODC,
            TRIM(XM.XML_OK) as XML_OK,
            TRIM(XM.XML_REJEIT) as XML_REJEIT,
            TRIM(XM.XML_CTEFOB) as XML_CTEFOB,
            XM.XML_FIL,
            XM.XML_EMIT,
            XM.XML_DEST,
            XM.XML_TPNF,
            XM.D_E_L_E_T_,
            CASE  
              WHEN TRIM(XM.XML_REJEIT) IS NOT NULL AND TRIM(XM.XML_REJEIT) <> ' ' THEN 'Rejeitada'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Classificada COM/FIS/LOG-Ok'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota COM/FIS/LOG-Ok'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Lançada COM/FIS/LOG-Ok'
              
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Classificada FIS/LOG-Ok'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota FIS/LOG-Ok'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Lançada FIS/LOG-Ok'
              
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') THEN 'Classificada LOG-Ok'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') THEN 'Pré-Nota LOG-Ok'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota LOG-Ok'
              
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' THEN 'Classificada COM-Ok'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' THEN 'Pré-Nota COM-Ok'
              
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' THEN 'Classificada'
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %'  THEN 'Pré-Nota'
              
              WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' THEN 'Lançada'
              
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'B' THEN 'Benef.Aberto' 
              
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'S' THEN 'NFS-e Aberto' 
              
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'D' THEN 'Dev.Venda Aberto' 
              
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'F' THEN 'CT-e FOB Aberto' 
              
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'T' THEN 'CT-e CIF Aberto' 
              
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N' THEN 'NF-e Aberto' 
              
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM-Ok'
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM/FIS-Ok'
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM/LOG-Ok'
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto LOG-Ok'
              WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto COM-Ok'
              ELSE 'Sem Definição'
            END as XML_STATUS
          FROM PROTHEUS11.CONDORXML XM
          WHERE XM.D_E_L_E_T_ = ' '
        ) XM
      ) XM
      WHERE XML_NUMNF LIKE '%890005574%' OR XML_NUMNF LIKE '%890005574011%'
    `;
    const resNF = await db.execute(sqlNF);
    console.log('Notas encontradas:', resNF);

    console.log('--- AMOSTRA DE FILIAIS EXISTENTES NO BANCO ---');
    const sqlFiliais = `
      SELECT DISTINCT XML_FIL, COUNT(*) as QTD 
      FROM PROTHEUS11.CONDORXML 
      WHERE D_E_L_E_T_ = ' '
      GROUP BY XML_FIL
      ORDER BY QTD DESC
    `;
    const resFiliais = await db.execute(sqlFiliais);
    console.log('Filiais e quantidades:', resFiliais);

  } catch (err) {
    console.error('Erro:', err);
  } finally {
    await db.close();
  }
}

debugNF();
