const db = require('../db');

const baseQuery = `
  SELECT XM.*,
    CASE
      WHEN XML_STATUS = 'Rejeitada' OR XML_STATUS LIKE 'Classificada%' OR XML_STATUS LIKE 'Lançada%' THEN 'Concluido'
      ELSE 'Pendente'
    END as XML_CATEGORIA
  FROM (
    SELECT 
      XM.XML_CHAVE,
      TRIM(XM.XML_NUMNF) as XML_NUMNF,
      TRIM(XM.XML_NOMEMT) as XML_NOMEMT,
      XM.XML_EMISSA,
      XM.XML_RECEB,
      XM.XML_DTRVLD,
      XM.XML_VLRDOC,
      TRIM(XM.XML_TIPODC) as XML_TIPODC,
      TRIM(XM.XML_OK) as XML_OK,
      TRIM(XM.XML_REJEIT) as XML_REJEIT,
      TRIM(XM.XML_CTEFOB) as XML_CTEFOB,
      XM.XML_FIL,
      XM.XML_EMIT,
      XM.XML_DEST,
      XM.XML_TPNF,
      XM.D_E_L_E_T_,
      -- Lógica de Filial Calculada
      CASE
        WHEN TRIM(XM.XML_FIL) IS NOT NULL AND TRIM(XM.XML_FIL) <> ' ' THEN TRIM(XM.XML_FIL)
        ELSE
          CASE
            WHEN TRIM(XM.XML_DEST) = '03613104121' AND TRIM(XM.XML_IEDEST) = '00000137398557' THEN '028501'
            WHEN TRIM(XM.XML_DEST) = '03613104121' AND TRIM(XM.XML_IEDEST) = '00000138284679' THEN '028503'
            WHEN TRIM(XM.XML_DEST) = '03613104121' AND TRIM(XM.XML_IEDEST) = '00000140259694' THEN '028505'
            WHEN TRIM(XM.XML_DEST) = '10158356001850' THEN '028503'
            WHEN TRIM(XM.XML_DEST) = '00073769100' AND TRIM(XM.XML_IEDEST) = '00000136631533' THEN '026702'
            WHEN TRIM(XM.XML_DEST) = '00073769100' AND TRIM(XM.XML_IEDEST) = '00000137276877' THEN '026703'
            WHEN TRIM(XM.XML_DEST) = '01847197981' AND TRIM(XM.XML_IEDEST) = '00000156158299' THEN '027902'
            WHEN TRIM(XM.XML_DEST) = '01847197981' AND TRIM(XM.XML_IEDEST) = '00000138682615' THEN '027903'
            WHEN TRIM(XM.XML_DEST) = '01847197981' AND TRIM(XM.XML_IEDEST) = '00000138938385' THEN '027904'
            WHEN TRIM(XM.XML_DEST) = '02076338195' AND TRIM(XM.XML_IEDEST) = '00000133192814' THEN '026601'
            WHEN TRIM(XM.XML_DEST) = '02076338195' AND TRIM(XM.XML_IEDEST) = '00000135809797' THEN '026602'
            WHEN TRIM(XM.XML_DEST) = '45909369172' AND TRIM(XM.XML_IEDEST) = '00000133256375' THEN '026001'
            WHEN TRIM(XM.XML_DEST) = '45909369172' AND TRIM(XM.XML_IEDEST) = '00000135467128' THEN '025801'
            WHEN TRIM(XM.XML_DEST) = '52392236968' AND TRIM(XM.XML_IEDEST) = '00000134652029' THEN '026901'
            WHEN TRIM(XM.XML_DEST) = '52392236968' AND TRIM(XM.XML_IEDEST) = '00000137527888' THEN '026903'
            WHEN TRIM(XM.XML_DEST) = '94178020110' AND TRIM(XM.XML_IEDEST) = '00000132179806' THEN '026101'
            WHEN TRIM(XM.XML_DEST) = '94178020110' AND TRIM(XM.XML_IEDEST) = '00000137120680' THEN '028101'
            WHEN TRIM(XM.XML_DEST) = '96945524949' AND TRIM(XM.XML_IEDEST) = '00000132874130' THEN '026201'
            WHEN TRIM(XM.XML_DEST) = '96945524949' AND TRIM(XM.XML_IEDEST) = '00000137299320' THEN '026202'
            WHEN TRIM(XM.XML_DEST) = '88211487187' AND TRIM(XM.XML_IEDEST) = '00000137273029' THEN '028401'
            WHEN TRIM(XM.XML_DEST) = '88211487187' THEN '020801'
            WHEN TRIM(XM.XML_DEST) = '06889621000154' THEN '010101'
            WHEN TRIM(XM.XML_DEST) = '58510168920' THEN '025902'
            WHEN TRIM(XM.XML_DEST) = '99470195191' THEN '026403'
            WHEN TRIM(XM.XML_DEST) = '01058947109' THEN '026501'
            WHEN TRIM(XM.XML_DEST) = '53733665104' THEN '028202'
            WHEN TRIM(XM.XML_DEST) = '02971375145' THEN '028601'
            ELSE NULL
          END
      END as XML_FIL_CALC,
      CASE  
         WHEN TRIM(XM.XML_REJEIT) IS NOT NULL AND TRIM(XM.XML_REJEIT) <> ' ' THEN 'Rejeitada'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Classificada COM/FIS/LOG-Ok'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota COM/FIS/LOG-Ok'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Lançada COM/FIS/LOG-Ok'
         
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Classificada FIS/LOG-Ok'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota FIS/LOG-Ok'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Lançada FIS/LOG-Ok'
         
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') THEN 'Classificada LOG-Ok'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') THEN 'Pré-Nota LOG-Ok'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota LOG-Ok'
         
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' THEN 'Classificada COM-Ok'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' THEN 'Pré-Nota COM-Ok'
         
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' THEN 'Classificada'
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %'  THEN 'Pré-Nota'
         
         WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' THEN 'Lançada'
         
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'B' THEN 'Benef.Aberto' 
         
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'S' THEN 'NFS-e Aberto' 
         
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'D' THEN 'Dev.Venda Aberto' 
         
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'F' THEN 'CT-e FOB Aberto' 
         
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'T' THEN 'CT-e CIF Aberto' 
         
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N' THEN 'NF-e Aberto' 
         
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM-Ok'
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM/FIS-Ok'
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM/LOG-Ok'
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto LOG-Ok'
         WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto COM-Ok'
         ELSE 'Sem Definição'
      END as XML_STATUS
    FROM PROTHEUS11.CONDORXML XM
    WHERE XM.D_E_L_E_T_ = ' '
      AND (XM.XML_TIPODC IN ('T', 'F') OR XM.XML_TPNF NOT IN ('0'))
      AND XM.XML_DEST <> XM.XML_EMIT
  ) XM
`;

async function testCalculatedFilial() {
  try {
    await db.initialize();
    
    // Testando buscar com filtro de filial '028503'
    const sql = `
      SELECT XML_NUMNF, XML_FIL_CALC, XML_STATUS, XML_NOMEMT, XML_VLRDOC
      FROM (${baseQuery}) XM
      WHERE XM.XML_FIL_CALC = '028503' AND XML_NUMNF LIKE '%890005574011%'
    `;
    const res = await db.execute(sql);
    console.log('Busca por Filial 028503 e NF 890005574011:', res);
    
  } catch (err) {
    console.error(err);
  } finally {
    await db.close();
  }
}

testCalculatedFilial();
