const db = require('../db');

const baseQuery = `
  SELECT XM.*,
    CASE
      WHEN XML_STATUS = 'Rejeitada' OR XML_STATUS LIKE 'Classificada%' OR XML_STATUS LIKE 'Lançada%' THEN 'Concluido'
      ELSE 'Pendente'
    END as XML_CATEGORIA
  FROM (
    SELECT 
      XM.XML_CHAVE,
      TRIM(XM.XML_NUMNF) as XML_NUMNF,
      TRIM(XM.XML_NOMEMT) as XML_NOMEMT,
      XM.XML_EMISSA,
      XM.XML_RECEB,
      XM.XML_DTRVLD,
      XM.XML_VLRDOC,
      TRIM(XM.XML_TIPODC) as XML_TIPODC,
      TRIM(XM.XML_OK) as XML_OK,
      TRIM(XM.XML_REJEIT) as XML_REJEIT,
      TRIM(XM.XML_CTEFOB) as XML_CTEFOB,
      TRIM(XM.XML_FIL) as XML_FIL,
      XM.XML_EMIT,
      XM.XML_DEST,
      XM.XML_TPNF,
      XM.D_E_L_E_T_,
      CASE  
        WHEN TRIM(XM.XML_REJEIT) IS NOT NULL AND TRIM(XM.XML_REJEIT) <> ' ' THEN 'Rejeitada'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Classificada COM/FIS/LOG-Ok'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota COM/FIS/LOG-Ok'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Lançada COM/FIS/LOG-Ok'
        
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Classificada FIS/LOG-Ok'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota FIS/LOG-Ok'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Lançada FIS/LOG-Ok'
        
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') THEN 'Classificada LOG-Ok'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') THEN 'Pré-Nota LOG-Ok'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' THEN 'Pré-Nota LOG-Ok'
        
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' THEN 'Classificada COM-Ok'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %' AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' THEN 'Pré-Nota COM-Ok'
        
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%|A%' THEN 'Classificada'
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' AND XM.XML_KEYF1 LIKE '%| %'  THEN 'Pré-Nota'
        
        WHEN TRIM(XM.XML_KEYF1) IS NOT NULL AND TRIM(XM.XML_KEYF1) <> ' ' THEN 'Lançada'
        
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'B' THEN 'Benef.Aberto' 
        
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'S' THEN 'NFS-e Aberto' 
        
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'D' THEN 'Dev.Venda Aberto' 
        
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'F' THEN 'CT-e FOB Aberto' 
        
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_TIPODC) = 'T' THEN 'CT-e CIF Aberto' 
        
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND (TRIM(XM.XML_CONFCO) IS NULL OR TRIM(XM.XML_CONFCO) = ' ') AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N' THEN 'NF-e Aberto' 
        
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM-Ok'
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_CONFIS) IS NOT NULL AND TRIM(XM.XML_CONFIS) <> ' ' AND (TRIM(XM.XML_DTRCTO) IS NULL OR TRIM(XM.XML_DTRCTO) = ' ') AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM/FIS-Ok'
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND (TRIM(XM.XML_CONFIS) IS NULL OR TRIM(XM.XML_CONFIS) = ' ') AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto + COM/LOG-Ok'
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_DTRCTO) IS NOT NULL AND TRIM(XM.XML_DTRCTO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto LOG-Ok'
        WHEN (TRIM(XM.XML_KEYF1) IS NULL OR TRIM(XM.XML_KEYF1) = ' ') AND TRIM(XM.XML_CONFCO) IS NOT NULL AND TRIM(XM.XML_CONFCO) <> ' ' AND TRIM(XM.XML_TIPODC) = 'N'  THEN 'NF-e Aberto COM-Ok'
        ELSE 'Sem Definição'
      END as XML_STATUS
    FROM PROTHEUS11.CONDORXML XM
    WHERE XM.D_E_L_E_T_ = ' '
      AND (XM.XML_TIPODC IN ('T', 'F') OR XM.XML_TPNF NOT IN ('0'))
      AND XM.XML_DEST <> XM.XML_EMIT
      AND XM.XML_EMISSA >= '20240601'
  ) XM
`;

async function runTest() {
  try {
    console.log('Inicializando pool...');
    await db.initialize();
    
    // 1. Contar Pendentes a partir de 20240601
    const countPendSql = `SELECT COUNT(*) as TOTAL FROM (${baseQuery}) XM WHERE XM.XML_CATEGORIA = 'Pendente'`;
    console.log('Executando contagem de Pendentes...');
    const resPend = await db.execute(countPendSql);
    console.log('Total Pendentes (a partir de 20240601):', resPend[0].TOTAL);
    
    // 2. Pegar amostra de Notas para ver a coluna XML_FIL
    const querySql = `
      SELECT * FROM (
        SELECT a.*, ROWNUM rnum FROM (
          SELECT 
            XM.XML_CHAVE,
            XM.XML_NUMNF,
            XM.XML_NOMEMT,
            XM.XML_EMISSA,
            XM.XML_RECEB,
            XM.XML_VLRDOC,
            XM.XML_STATUS,
            XM.XML_CATEGORIA,
            XM.XML_FIL,
            XM.XML_FIL_CALC,
            CASE 
              WHEN REGEXP_LIKE(TRIM(COALESCE(TRIM(XM.XML_RECEB), XM.XML_EMISSA)), '^[0-9]{8}$') 
              THEN ROUND(SYSDATE - TO_DATE(TRIM(COALESCE(TRIM(XM.XML_RECEB), XM.XML_EMISSA)), 'YYYYMMDD'))
              ELSE NULL 
            END as DIAS
          FROM (${baseQuery}) XM
          ORDER BY DIAS DESC NULLS LAST
        ) a WHERE ROWNUM <= 5
      ) WHERE rnum > 0
    `;
    console.log('Pegando 5 notas fiscais com a coluna XML_FIL e XML_FIL_CALC...');
    const rows = await db.execute(querySql);
    console.log('Amostra de Notas (com XML_FIL e XML_FIL_CALC):');
    rows.forEach(r => {
      console.log(`- NF ${r.XML_NUMNF} | Emissão: ${r.XML_EMISSA} | XML_FIL: "${r.XML_FIL}" | XML_FIL_CALC: "${r.XML_FIL_CALC}" | Status: ${r.XML_STATUS}`);
    });

  } catch (err) {
    console.error('Erro no teste:', err);
  } finally {
    await db.close();
  }
}

runTest();
